---
fail_fast: false
minimum_pre_commit_version: "2.6.0"
repos:
  -
    repo: https://github.com/aws-ia/pre-commit-configs
    # To update run:
    # pre-commit autoupdate --freeze
    rev: v1.5.0
    hooks:
      - id: aws-ia-meta-hook